const cardsData = [
    { id: 1, image: "images/card1.webp", heroImage: "images/card1.webp", bossImage: "images/boss1.webp", glowClass: "glow-1", name: "П.Е.К.К.А.", rarity: "⚡ Эпическая", elixir: 7, description: "Медленный воин ближнего боя в тяжёлой броне. Наносит огромный урон.", hp: "4 982", damage: "1 081", attackSpeed: "1.8 сек", target: "Наземные", speed: "Медленная", rarityValue: "Эпическая" },
    { id: 2, image: "images/card2.webp", heroImage: "images/card2.webp", bossImage: "images/boss2.webp", glowClass: "glow-2", name: "Мега-рыцарь", rarity: "⭐ Легендарная", elixir: 7, description: "Мощный танк, который прыгает на врагов и наносит урон при приземлении.", hp: "3 300", damage: "480", attackSpeed: "1.7 сек", target: "Наземные", speed: "Средняя", rarityValue: "Легендарная" },
    { id: 3, image: "images/card3.webp", heroImage: "images/card3.webp", bossImage: "images/boss3.webp", glowClass: "glow-3", name: "Валькирия", rarity: "🟡 Редкая", elixir: 4, description: "Крушит всех врагов вокруг своим топором. Отличная защита от толп.", hp: "1 650", damage: "220", attackSpeed: "1.5 сек", target: "Наземные", speed: "Средняя", rarityValue: "Редкая" },
    { id: 4, image: "images/card4.webp", heroImage: "images/card4.webp", bossImage: "images/boss4.webp", glowClass: "glow-4", name: "Маг", rarity: "⚡ Эпическая", elixir: 5, description: "Могущественный заклинатель, атакующий огненными шарами. Наносит урон по области.", hp: "598", damage: "293", attackSpeed: "1.6 сек", target: "Воздушные и наземные", speed: "Средняя", rarityValue: "Эпическая" },
    { id: 5, image: "images/card5.webp", heroImage: "images/card5.webp", bossImage: "images/boss5.webp", glowClass: "glow-5", name: "Принцесса", rarity: "⭐ Легендарная", elixir: 3, description: "Стреляет из лука на огромное расстояние. Снайпер с самой дальней дистанцией.", hp: "216", damage: "140", attackSpeed: "3.0 сек", target: "Воздушные и наземные", speed: "Средняя", rarityValue: "Легендарная" },
    { id: 6, image: "images/card6.webp", heroImage: "images/card6.webp", bossImage: "images/boss6.webp", glowClass: "glow-1", name: "Великан", rarity: "🟡 Редкая", elixir: 5, description: "Огромный танк с большим запасом здоровья. Целится только в здания.", hp: "3 840", damage: "210", attackSpeed: "1.5 сек", target: "Здания", speed: "Медленная", rarityValue: "Редкая" },
    { id: 7, image: "images/card7.webp", heroImage: "images/card7.webp", bossImage: "images/boss7.webp", glowClass: "glow-3", name: "Дракон", rarity: "⚡ Эпическая", elixir: 4, description: "Летающий дракон, дышащий огнём по области. Отлично против толп.", hp: "1 024", damage: "120", attackSpeed: "1.8 сек", target: "Воздушные и наземные", speed: "Средняя", rarityValue: "Эпическая" },
    { id: 8, image: "images/card8.webp", heroImage: "images/card8.webp", bossImage: "images/boss8.webp", glowClass: "glow-4", name: "Лучница", rarity: "🟢 Обычная", elixir: 3, description: "Дальнобойный отряд из двух лучниц. Высокая скорость атаки.", hp: "250", damage: "70", attackSpeed: "1.2 сек", target: "Воздушные и наземные", speed: "Средняя", rarityValue: "Обычная" }
];
const DEFAULT_CARD_IMG = "images/default.webp";